---
# Print vars
- name: Print vars
  debug:
    msg: '{{ image_name }} {{ tag }}'

- name: Create a Busybox deployment
  k8s:
    kubeconfig: /cluster/config
    state: present
    src: /kubernetes/deployments/busybox.yml
...