---
# Install curl, openssh-server, python3, python3-pip
- name: Install packages
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - curl
    - openssh-server
    - python3
    - python3-pip

# Install openshift
- name: Install openshift
  shell: pip3 install openshift
  args:
    executable: /bin/bash

# Create development namespace
- name: Create a k8s namespace
  k8s:
    kubeconfig: cluster/config
    name: development
    api_version: v1
    kind: Namespace
    state: present

# Create production namespace
- name: Create a k8s namespace
  k8s:
    kubeconfig: cluster/config
    name: production
    api_version: v1
    kind: Namespace
    state: present

# Fetch list of kubernetes namespace
- name: Fetch a list of namespaces
  set_fact:
    projects: "{{ lookup('k8s', api_version='v1', kind='Namespace') }}"
...