apiVersion: v1
kind: Service
metadata:
  name: sample-api-service
  namespace: "{{ env }}"
spec:
  type: LoadBalancer
  selector:
    app: sample-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000