---
# Hosts
all:
  hosts:
    # Production Host
    production:
      ansible_connection: local
      ansible_user: root
      ansible_host: 192.168.99.101
      ansible_port: 6443

    # Development Host
    development:
      ansible_connection: local
      ansible_user: root
      ansible_host: 192.168.99.101
      ansible_port: 6443
...
